


db.pool.size = 5

#//work
#db.url=jdbc:sqlite:F:/IDEA_Projects/!Database/mybaseFor3.db

#// home
#db.url=jdbc:sqlite:D:/java/DATABASES/mybaseFor3.db

//deploy
#db.url=jdbc:sqlite:/var/lib/myBase/mybaseFor3.db

