# ??? ?????? - db.url=jdbc:sqlite:F:/IDEA_Projects/!Database/mybaseFor3.db

db.url=jdbc:sqlite:F:/IDEA_Projects/!Database/mybaseFor3.db
#db.url=jdbc:sqlite:D:/java/DATABASES/mybaseFor3.db
#db.url=jdbc:sqlite:F:/DATABASES/mybaseFor3.db


db.pool.size = 5

